name: Core
version: '${project.version}'
main: me.cfcore.core.Core
api-version: '1.20'
commands:
  level:
    description: sets your level
    usage: <command>
  exp:
    description: sets your exp
    usage: <command>
  class:
    description: sets your class
    usage: <command>